# Generated by Django 4.2.11 on 2024-04-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
