# Generated by Django 4.2.11 on 2024-04-18 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0002_delete_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product1',
            new_name='Product',
        ),
    ]
