# Generated by Django 4.2.11 on 2024-04-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0003_rename_product1_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
