# Generated by Django 4.2.11 on 2024-04-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0005_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=500)),
                ('speed', models.IntegerField(default=50)),
            ],
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
