# Generated by Django 4.2.11 on 2024-04-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0009_cart_cartitem_order_orderitem_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
