# Generated by Django 4.2.11 on 2024-04-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0011_shippinginfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingInfo',
        ),
    ]
