# Generated by Django 4.2.11 on 2024-05-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0013_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
