# Generated by Django 4.2.11 on 2024-05-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0014_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sub_total',
            field=models.IntegerField(default=0),
        ),
    ]
