# Generated by Django 4.2.11 on 2024-05-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0015_cart_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='sub_total',
            field=models.IntegerField(default=1),
        ),
    ]
