# Generated by Django 4.2.11 on 2024-05-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0016_alter_cart_sub_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('state_country', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=200)),
                ('apartment_suite', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('create_account', models.BooleanField(default=False)),
                ('ship_to_different_address', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CartTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
