# Generated by Django 4.2.11 on 2024-05-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0017_billingdetails_carttotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='product'),
        ),
    ]
